### ISSUE TITLE
Add a Download Button

### ISSUE THREAD

**Issue by jai-dewani** [jai-dewani/Meme-App#10]
Add a download button so as the user can easily download their hot meme :p

**Comment by MilePaor** [comment]
Hello @jai-dewani can i take this one?

**Comment by jai-dewani** [comment]
Sure @MilePaor, Go ahead!

**Comment by FajarSJ** [comment]
Hi @jai-dewani, can i take this one too?

**Comment by jai-dewani** [comment]
Sorry @FajarSJ but I have assigned the issue as he reached out first, you could check out other issues or maybe open a new one if you find some bug or a new feature in sight

**Comment by FajarSJ** [comment]
That's okay @jai-dewani, i think i will open a new one
