### ISSUE TITLE
👋 Hi, I just want to add Responsive Feature when reach mobile device

### ISSUE THREAD

**Issue by FajarSJ** [jai-dewani/Meme-App#15]
Hi Everyone, i just want to add Responsive feature that shown below.

![image](https://user-images.githubusercontent.com/22906687/94989146-be428680-059c-11eb-9d95-5275a5b11bb0.png)

Please let me know if you need this feature and i'll make PR for it

**Comment by jai-dewani** [comment]
Sure this, would be lovely @FajarSJ

**Comment by FajarSJ** [comment]
Awesome, i already create a PR can you please kindly check it @jai-dewani 

here the link to the PR : https://github.com/jai-dewani/Meme-App/pull/16

**Comment by jai-dewani** [comment]
The PR was merged, hence I am closing this Issue
