### ISSUE TITLE
Allow dragging of text over image

### ISSUE THREAD

**Issue by jai-dewani** [jai-dewani/Meme-App#2]
As of new people can only add text on top and bottom,
Can we allow the user to drag the text over the image?

**Comment by jai-dewani** [comment]
Use this for a better understanding: http://jsfiddle.net/m1erickson/9xAGa/

**Comment by itsvvishnu** [comment]
can you assign it to me?

**Comment by jai-dewani** [comment]
Sorry @itsvvishnu, actually this issue should have been closed, this functionality has been already added.
