### ISSUE TITLE
Able to submit multiple time

### ISSUE THREAD

**Issue by Ian-Yy** [jai-dewani/Meme-App#21]
Currently, I can click submit multiple time and multiple text will be added to the meme. 

Expected Behaviour: It should not create multiple text or introduce clear to remove all of them

**Comment by jai-dewani** [comment]
Yeah @Ian-Yy this is a problem right now, 
if you wish you can create a PR to solve it. I don't think anyone else is working on this problem right now

**Comment by Ian-Yy** [comment]
Since this is merged, can I close this issue?

**Comment by jai-dewani** [comment]
Yeah, I am closing this issue
