### ISSUE TITLE
Allow user to drag an custom image

### ISSUE THREAD

**Issue by jai-dewani** [jai-dewani/Meme-App#6]
Refer: https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_ondrag

**Comment by jai-dewani** [comment]
Duplicate #4

**Comment by elenirotsides** [comment]
Hi @jai-dewani , I'd love to give this a try! I'm a beginner web programming enthusiast, so this might take me a little while, but I'm confident that I can get it done! Please let me know what you think when you get a chance :)
